version: "3.9"

services:
  db:
    image: postgres:16.1-alpine3.19
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}